excluded:
    - .build
    - .swiftpm
    - Package.swift
    - Tests/LinuxMain.swift
    - "*/XCTestManifests.swift"
    - Examples
    - .github

included:
    - Source
    - Tests

disabled_rules:
    - trailing_whitespace
    - for_where
    - opening_brace
    - trailing_comma
    - nesting

opt_in_rules:
    - empty_count
    - empty_string

line_length:
    warning: 120
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 80
    error: 150

file_length:
    warning: 500
    error: 1000
    ignore_comment_only_lines: true

type_body_length:
    warning: 400
    error: 600

cyclomatic_complexity:
    warning: 15
    error: 25
    ignores_case_statements: true

identifier_name:
    min_length:
        warning: 2
    excluded:
        - id
        - db
        - i
        - j
        - x
        - y
