name: Code Quality

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  format:
    name: Swift Format Check
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"

    - name: Check code formatting
      run: |
        swift package plugin --allow-writing-to-package-directory format --lint || true
      continue-on-error: true

  documentation:
    name: Documentation Check
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"

    - name: Build documentation
      run: |
        swift package generate-documentation || echo "Documentation generation not configured"
      continue-on-error: true

  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run security audit
      run: |
        # Check for known security issues in dependencies
        echo "Security audit placeholder - configure as needed"
      continue-on-error: true
