name: Code Quality

on:
    pull_request:
        branches: [main, dev]

jobs:
    format:
        name: Swift Format Check
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Show Swift version
              run: swift --version

            - name: Check code formatting
              run: |
                  swift package plugin --allow-writing-to-package-directory format --lint || true
              continue-on-error: true

    documentation:
        name: Documentation Check
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Show Swift version
              run: swift --version

            - name: Build documentation
              run: |
                  swift package generate-documentation || echo "Documentation generation not configured"
              continue-on-error: true
