name: Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-macos-intel:
        name: Build macOS Intel
        runs-on: macos-13

        steps:
            - uses: actions/checkout@v4

            - name: Show Swift version
              run: swift --version

            - name: Build release binary
              run: |
                  swift build -c release --arch x86_64
                  cp .build/release/vapor-make-migration vapor-make-migration-macos-x64
                  chmod +x vapor-make-migration-macos-x64

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: vapor-make-migration-macos-x64
                  path: vapor-make-migration-macos-x64

    build-macos-arm:
        name: Build macOS ARM64
        runs-on: macos-14

        steps:
            - uses: actions/checkout@v4

            - name: Show Swift version
              run: swift --version

            - name: Build release binary
              run: |
                  swift build -c release --arch arm64
                  cp .build/release/vapor-make-migration vapor-make-migration-macos-arm64
                  chmod +x vapor-make-migration-macos-arm64

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: vapor-make-migration-macos-arm64
                  path: vapor-make-migration-macos-arm64

    build-linux:
        name: Build Linux
        runs-on: ubuntu-latest
        container:
            image: swift:6.0

        steps:
            - uses: actions/checkout@v4

            - name: Show Swift version
              run: swift --version

            - name: Build release binary
              run: |
                  swift build -c release
                  cp .build/release/vapor-make-migration vapor-make-migration-linux-x64
                  chmod +x vapor-make-migration-linux-x64

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: vapor-make-migration-linux-x64
                  path: vapor-make-migration-linux-x64

    create-release:
        name: Create GitHub Release
        needs: [build-macos-intel, build-macos-arm, build-linux]
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Download all artifacts
              uses: actions/download-artifact@v4

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      vapor-make-migration-macos-x64/vapor-make-migration-macos-x64
                      vapor-make-migration-macos-arm64/vapor-make-migration-macos-arm64
                      vapor-make-migration-linux-x64/vapor-make-migration-linux-x64
                  body: |
                      ## Vapor Make Migration ${{ github.ref_name }}

                      Auto-generate Vapor migration files by comparing Fluent models with your database schema.

                      ### Installation

                      #### macOS (Apple Silicon)
                      ```bash
                      curl -L -o vapor-make-migration https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/vapor-make-migration-macos-arm64
                      chmod +x vapor-make-migration
                      sudo mv vapor-make-migration /usr/local/bin/
                      ```

                      #### macOS (Intel)
                      ```bash
                      curl -L -o vapor-make-migration https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/vapor-make-migration-macos-x64
                      chmod +x vapor-make-migration
                      sudo mv vapor-make-migration /usr/local/bin/
                      ```

                      #### Linux
                      ```bash
                      curl -L -o vapor-make-migration https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/vapor-make-migration-linux-x64
                      chmod +x vapor-make-migration
                      sudo mv vapor-make-migration /usr/local/bin/
                      ```

                      ### Usage

                      ```bash
                      # Preview changes
                      vapor-make-migration --database postgres://user:pass@localhost/db --preview

                      # Generate migration
                      vapor-make-migration -d postgres://user:pass@localhost/db --name AddUserTable
                      ```

                      See [documentation](https://github.com/${{ github.repository }}) for more details.
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
