name: Tests

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    test-macos:
        name: Test on macOS
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Show Swift version
              run: swift --version

            - name: Cache Swift packages
              uses: actions/cache@v4
              with:
                  path: .build
                  key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift') }}
                  restore-keys: |
                      ${{ runner.os }}-spm-

            - name: Build
              run: swift build -v

            - name: Run tests
              run: swift test -v

            - name: Build release
              run: swift build -c release

    test-linux:
        name: Test on Linux
        runs-on: ubuntu-latest
        container:
            image: swift:6.0

        steps:
            - uses: actions/checkout@v4

            - name: Show Swift version
              run: swift --version

            - name: Cache Swift packages
              uses: actions/cache@v4
              with:
                  path: .build
                  key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift') }}
                  restore-keys: |
                      ${{ runner.os }}-spm-

            - name: Build
              run: swift build -v

            - name: Run tests
              run: swift test -v

    lint:
        name: SwiftLint
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: SwiftLint
              uses: norio-nomura/action-swiftlint@3.2.1
              continue-on-error: true
